AI/self_instruct/generate_instruction.py
AI/self_instruct/gpt_api.py

[gpt api를 이용한 self-instruct 코드 구현 ](#9  )
- gpt-3.5-turbo model을 이용하여 seed data인 226 instruction에서 10031 instruction 확보

[AI/feat] gpt api를 이용한 self-instruct 코드 구현 

---

BE/exceed/src/main/java/com/gaebaljip/exceed/common/DecimalUtil.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/CreateMemberRequest.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/CurrentMeal.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/GetMealNutritionResponse.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/MaintainMeal.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/TargetMeal.java
BE/exceed/src/main/java/com/gaebaljip/exceed/food/domain/FoodModel.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/GetMealController.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetCurrentMealService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/domain/MealModel.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/port/in/GetCurrentMealQuery.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/port/out/LoadMealPort.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/in/CreateMemberController.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/CreateMemberService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetMaintainMealService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetTargetMealService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/CreateMemberCommand.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/CreateMemberUsecase.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/GetMaintainMealUsecase.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/in/GetTargetMealUsecase.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/port/out/LoadMemberPort.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/Activity.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/MemberModel.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/domain/PhysiqueModel.java
BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/GetMealControllerTest.java
BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/CreateMemberControllerTest.java
BE/exceed/src/test/java/com/gaebaljip/exceed/member/application/CreateMemberServiceTest.java
BE/exceed/src/test/java/com/gaebaljip/exceed/member/domain/PhysiqueModelTest.java

https://github.com/JNU-econovation/Gaebaljip/issues/6
- 유지 및 목표 칼로리 구하는 유스케이스 구현
- 현재 칼로리 구하는 유스케이스 구현
- MealModel 및 FoodModel 생성
DB 연결 X

[BE/feat] 필요 칼로리들을 계산하여 반환하는 유스케이스 구현

---

AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/request/FoodInfoRequestDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/request/FoodRegistrationRequestDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/request/OnboardingRequestDTO.kt

close #18 
model - dto - request 패키지를 생성 및 RequestDTO 파일들 생성
model.dto.request 패키지 내 RequestDTO 파일 생성
- OnboardingRequestDTO =  온보딩 요청
- FoodInfoRequestDTO = 음식 정보 요청
- FoodRegistrationRequestDTO = 섭취 음식 등록 요청

[AOS/feat] : request DTO 패키지 및 파일 생성

---

BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/adapter/in/GetAchieveController.java
BE/exceed/src/main/java/com/gaebaljip/exceed/achieve/application/GetAchieveService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/GetFood.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/GetMeal.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/GetMealFood.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/GetMealFoodResponse.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/GetMealResponse.java
BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodsPersistenceAdapter.java
BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/out/LoadFoodsSpecificDate.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/GetMealController.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealPersistenceAdapter.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetFoodService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetSpecificMealService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/GetFoodQuery.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/GetSpecificMealQuery.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/adapter/out/persistence/MemberPersistenceAdapter.java
BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/GetMealControllerTest.java
BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/CreateMemberControllerTest.java

https://github.com/JNU-econovation/Gaebaljip/issues/21
- GetSpecificMealQuery : 특정 식사에 먹은 음식들을 조회하는 유스케이스
- GetFoodQuery : 특정 음식을 조회하는 유스케이스
테스트 코드 주석 -> 회원 생성 웹 어댑터 오류

[BE/feat] 특정 일자 식사 분석해주는 유스케이스 구현

---

BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/DailyMeal.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetFood.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetMealFoodResponse.java
BE/exceed/src/main/java/com/gaebaljip/exceed/food/adapter/out/FoodConverter.java
BE/exceed/src/main/java/com/gaebaljip/exceed/food/domain/FoodModel.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/in/GetMealController.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/adapter/out/MealConverter.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetCurrentMealService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetFoodService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetSpecificMealService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/port/in/GetCurrentMealQuery.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/domain/MealModel.java
BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/GetMealIntegrationTest.java
BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/GetMealControllerTest.java

https://github.com/JNU-econovation/Gaebaljip/issues/37
- GetSpecificMealQuery 구현
- /v1/meal/{date} -> /v1/meal 변경
- /v1/meal/{date}/food -> /v1/meal/{date} 변경

[BE/feat] 해당 일자의 식사 정보 분석하여 제공하는 기능 구현

---

AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/CalendarDetailResponseDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/CalendarInfoResponseDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/FoodInfoResponseDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/FoodListPagingResponseDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/HomeInfoResponseDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/OnboardingResponseDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/RegisterFoodInfoResponseDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/common/CommonMealInfo.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/common/CommonResponseDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/common/ErrorStatusDTO.kt

close JNU-econovation/Gaebaljip#17
API 요청의 결과를 받아올 DTO를 생성했습니다.
API문서에 맞도록 DTO 생성
추천화면 DTO의 경우 아직 추천화면의 구조가 잘 잡히지 않았기에 추후에 작성합니다.

[AOS/setting] API Response DTO들 생성

---

AOS/app/build.gradle.kts
AOS/build.gradle.kts

close JNU-econovation/Gaebaljip#45
firebase analytics를 사용 설정했습니다.
- Firebase SDK를 사용 설정 했습니다.
- 원래 MainApplication을 생성하고 uncaughtException을 analytics로 로깅하려 했으나, 확인결과 Firebase에서 해당 이벤트는 자동으로 로깅해줘 작성하지 않았습니다.

[AOS/setting] Analytics 사용 설정

---

BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/CurrentMeal.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/DailyMeal.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/GetFood.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/MaintainMeal.java
BE/exceed/src/main/java/com/gaebaljip/exceed/dto/response/TargetMeal.java
BE/exceed/src/main/java/com/gaebaljip/exceed/food/application/GetFoodService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetCurrentMealService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetSpecificMealService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetMaintainMealService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetTargetMealService.java
BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/GetMealIntegrationTest.java

https://github.com/JNU-econovation/Gaebaljip/issues/47
- v1/meal 의 응답 DTO의 prefix 수정
- v1/meal{date}  응답 DTO의 변수명 위치 수정

[BE/feat] FE 요청에따른 응답 DTO 수정

---

AOS/app/src/main/java/com/gaebaljip/exceed/ui/common/AchieveGaugeComponent.kt
AOS/app/src/main/res/values/colors.xml

close JNU-econovation/Gaebaljip#50
진행도 게이지 컴포넌트를 생성
- color.xml에 색상 등록
- 진행도 게이지 컴포넌트 생성
- 폰트의 경우 다른 개발자 분과 겹칠 수 있어 추후 적용

[AOS/feat] 진행도 게이지

---

BE/exceed/src/main/java/com/gaebaljip/exceed/security/JwtAuthenticationFilter.java
BE/exceed/src/main/resources/db/schema.sql

https://github.com/JNU-econovation/Gaebaljip/issues/73
- schema에 MESSAGE_TB 추가
- JwtAuthenticationFilter에서 JWT 토큰 유무 검사하는 if문에 retrun 추가하여 해당 에러 해결

[BE/hotfix] 요청 1번에 응답 2개가 합쳐서 오는 오류 해결

---

AOS/app/src/main/java/com/gaebaljip/exceed/MainActivity.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/add/AddScreen.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/add/AddViewModel.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/alarm/AlarmInfo.kt
AOS/app/src/main/res/drawable/check_icon.xml
AOS/app/src/main/res/values/colors.xml

close JNU-econovation/Gaebaljip#82
AddScreen UI 배치
- AddScreen 패키지 이동
- AddScreen 컴포넌트 배치
- Alarm Info Class 변경
- AddViewmodel 생성

[AOS/feat] Add Screen UI

---

AOS/app/src/main/java/com/gaebaljip/exceed/screens/LoginScreen.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/OnboardingScreen.kt

close #89 
- 로그인, 온보딩 화면 UI 배치

[AOS/feat] 로그인, 온보딩 UI 추가

---

AOS/app/build.gradle.kts
AOS/app/src/main/AndroidManifest.xml
AOS/app/src/main/java/com/gaebaljip/exceed/MainApplication.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/MainRepository.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/local/AlarmDAO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/local/AlarmDatabase.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/local/AlarmEntity.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/local/LocalDataSource.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/local/TypeConverter.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/add/AddScreen.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/add/AddViewModel.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/alarm/AlarmScreen.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/alarm/AlarmViewModel.kt
AOS/app/src/main/res/values/colors.xml

close JNU-econovation/Gaebaljip#84
Room DB 연결
- Room DB 사용 설정
- 데이터 베이스 생성
- DAO 생성
- 엔티티 생성
- 로컬 데이터 소스 생성
- 메인 레파지토리 생성
- 알람 화면 Room과 연결

[AOS/feat] Room DB 연결

---

AOS/app/build.gradle.kts
AOS/app/src/main/java/com/gaebaljip/exceed/APIService.kt
AOS/app/src/main/java/com/gaebaljip/exceed/ActiveTypeEnum.kt
AOS/app/src/main/java/com/gaebaljip/exceed/OnboardingViewModel.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/request/OnboardingRequestDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/MainRepository.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/OnboardingScreen.kt

[AOS/feat] 온보딩 입력 데이터와 ViewModel, RequestDTO 연결

---

BE/exceed/src/main/java/com/gaebaljip/exceed/meal/application/GetCurrentMealService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetMaintainMealService.java
BE/exceed/src/main/java/com/gaebaljip/exceed/member/application/GetTargetMealService.java
BE/exceed/src/test/java/com/gaebaljip/exceed/achieve/GetAchieveIntegrationTest.java
BE/exceed/src/test/java/com/gaebaljip/exceed/common/util/ApiDocumentUtil.java
BE/exceed/src/test/java/com/gaebaljip/exceed/food/GetFoodIntegrationTest.java
BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/GetMealIntegrationTest.java
BE/exceed/src/test/java/com/gaebaljip/exceed/meal/adapter/in/EatMealControllerTest.java
BE/exceed/src/test/java/com/gaebaljip/exceed/member/CreateGuestIntegrationTest.java
BE/exceed/src/test/java/com/gaebaljip/exceed/member/adapter/in/CreateGuestControllerTest.java

https://github.com/JNU-econovation/Gaebaljip/issues/98
- prettyPrint() 적용
- request 및 response 상세 설명 추가

[BE/docs] Rest Docs 보충

---

BE/exceed/src/main/java/com/gaebaljip/exceed/config/WebConfig.java

- https://github.com/JNU-econovation/Gaebaljip/issues/102
- WebMvcConfiguration -> WebMvcConfigurer로 교체

fix/#102 : WebMvcConfiguration -> WebMvcConfigurer로 교체

---

AI/server/core/config.py
AI/server/db/crud.py
AI/server/db/database.py
AI/server/db/models.py
AI/server/db/schemas.py
AI/server/main.py

- sqlalchemy import 오류 interpreter 경로 설정으로 해결
- close #109

[AI/feat] 챗봇 서버 DB 연결

---

AI/server/main.py

close #112 
- 로그 확인을 위한 함수 정의
- 토큰에서 memberId 추출을 위한 get_current_member 함수 정의

[AI/feat] 챗봇 서버 JWT Token Decode

---

AI/server/main.py
AI/server/test/curl.py

feat: Curl을 이용한 Test 진행

---

AI/server/.gitignore
AI/server/core/config.py

[AI/feat] 환경 변수 설정

---

AI/server/main.py

close #118 
- 환경 변수의 value 값 변경 진행

[AI/fix] .env value 값 변경

---

AI/server/core/config.py
AI/server/main.py

[AI/feat] 배포를 위한 환경변수 변경

---

AOS/app/src/main/java/com/gaebaljip/exceed/APIService.kt
AOS/app/src/main/java/com/gaebaljip/exceed/FoodViewModel.kt
AOS/app/src/main/java/com/gaebaljip/exceed/OnboardingViewModel.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/request/ChattingRequestDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/ChattingResponseDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/MainRepository.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/remote/RemoteDataSource.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/FoodScreen.kt
AOS/app/src/main/res/drawable/send_icon.xml

close #104 
- 화면 UI 구성
- ViewModel, DTO 생성
- 챗봇 서버와 retrofit 통신을 위해 관련 코드 수정

[AOS/feat] 음식 추천 챗봇 화면 구현

---

AOS/app/src/main/java/com/gaebaljip/exceed/APIService.kt
AOS/app/src/main/java/com/gaebaljip/exceed/FoodViewModel.kt
AOS/app/src/main/java/com/gaebaljip/exceed/OnboardingViewModel.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/request/ChattingRequestDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/ChattingResponseDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/MainRepository.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/remote/RemoteDataSource.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/FoodScreen.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/calendar/CalendarScreen.kt
AOS/app/src/main/java/com/gaebaljip/exceed/ui/theme/Type.kt
AOS/app/src/main/res/drawable/send_icon.xml

close #106 
- 캘린더 DTO와 연결된 데이터들의 상태를 저장하는 리스트에서 index error를 getOrNull을 사용하여 수정했습니다.

[AOS/fix] 캘린더 화면 전환 버그 수정

---

AOS/app/src/main/AndroidManifest.xml
AOS/app/src/main/java/com/gaebaljip/exceed/APIService.kt
AOS/app/src/main/java/com/gaebaljip/exceed/RegistrationActivity.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/request/FoodRegistrationRequestDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/MainRepository.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/local/LocalDataSource.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/remote/InputStreamRequestBody.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/remote/RemoteDataSource.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/add/AddScreen.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/add/AddViewModel.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/registration/RegistrationScreen.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/registration/RegistrationViewModel.kt
AOS/app/src/main/res/values/strings.xml

close #85 
- 레트로핏 관련 메서드들 추가
- 컴포넌트 배치

[AOS/feat] 음식 등록 요청

---

AI/server/main.py

close #125 
- get_currnet_member 함수 재정의

[AI/feat] 로그 메시지 시간 출력

---

AOS/app/src/main/java/com/gaebaljip/exceed/APIService.kt
AOS/app/src/main/java/com/gaebaljip/exceed/FoodViewModel.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/request/ChattingRequestDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/dto/response/CalendarInfoResponseDTO.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/MainRepository.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/remote/RemoteDataSource.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/FoodScreen.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/calendar/CalendarScreen.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/calendar/CalendarViewModel.kt
AOS/app/src/main/res/drawable/back_icon.xml
AOS/app/src/main/res/drawable/forward_icon.xml

[AOS/feat] DEV 전 merge

---

AI/server/main.py

[AI/fix] response 변수 이름 변경

---

AOS/app/src/main/java/com/gaebaljip/exceed/FoodViewModel.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/MainRepository.kt
AOS/app/src/main/java/com/gaebaljip/exceed/model/repository/remote/RemoteDataSource.kt
AOS/app/src/main/java/com/gaebaljip/exceed/screens/FoodScreen.kt

[AOS/feat] 챗봇 답변 수신
